### ISSUE TITLE
Join forces on MattermostAPI client?

### ISSUE THREAD

**Issue by thePanz** [gnello/php-mattermost-driver#21]
I am the author of https://github.com/thePanz/MattermostClient
What about joining forces? :)

**Comment by gnello** [comment]
Hi!
I would appreciate your help, what do you have in mind?

**Comment by thePanz** [comment]
Maybe in a merge of our works, I noticed that your library is mostly exposing raw responses, while mine also focus on creating a models+builders.
I also opt to not rely on Guzzle, but on PhpHttp abstraction.

WDYT?

**Comment by gnello** [comment]
I respect your point but I would like to keep this project as simpliest as possible, which is why this library exposes raw response and doesn't use models or builders. 
Despite my point of view maybe we can create a new repo only with your models and builders made compatible with this project and include it in the documentation.
